#define END_OF_FILE 0
#define CLASS_KW 1
#define PUBLIC_KW 2
#define STATIC_KW 3
#define VOID_KW 4
#define MAIN_KW 5
#define LPAREN 6
#define STRING_KW 7
#define LBRACKET 8
#define RBRACKET 9
#define RPAREN 10
#define LBRACE 11
#define RBRACE 12
#define EXTENDS_KW 13
#define SEMICOLON 14
#define INT_KW 15
#define BOOLEAN_KW 16
#define IF_KW 17
#define ELSE_KW 18
#define WHILE_KW 19
#define PRINTLN_KW 20
#define AND 21
#define LT 22
#define PLUS 23
#define MINUS 24
#define TIMES 25
#define DOT 26
#define LENGTH_KW 27
#define COMMA 28
#define TRUE_KW 29
#define FALSE_KW 30
#define THIS_KW 31
#define NEW_KW 32
#define NOT 33
#define RETURN_KW 34
#define IDENTIFIER 35
#define INTEGER 36
#define EQUALS 37
#define UNKNOWN 38
